=== NguyenHoang1303/t2012e_xml/users.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">
    <xs:element name="users">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="user" type="user" maxOccurs="unbounded"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:group name="information">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="age">
                <xs:simpleType>
                    <xs:restriction base="xs:integer" >
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="120"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:complexType name="employeeInformation">
        <xs:sequence>
            <xs:group ref="information"/>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="department" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="teacherInformation">
        <xs:sequence>
            <xs:group ref="information"/>
            <xs:element name="experience" type="xs:integer"/>
            <xs:element name="class" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="user">
        <xs:choice>
            <xs:element name="employee" type="employeeInformation"/>
            <xs:element name="teacher" type="teacherInformation"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== NguyenHoang1303/t2012e_xml/users.xml
<?controller version="1.0"?>

<users
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com/xml users.xsd">
    <user>
        <employee id="1">
            <firstName>Hoang</firstName>
            <lastName>Nguyen</lastName>
            <email>hoangnguyen@gmail.com</email>
            <phone>0969451691</phone>
            <age>25</age>
            <position>dev</position>
            <department>IT</department>
        </employee>
    </user>
    <user>
        <teacher id="1">
            <firstName>Xuan Hung</firstName>
            <lastName>Dao</lastName>
            <email>XuanHung@gmail.com</email>
            <phone>09090909</phone>
            <age>18</age>
            <experience>-10</experience>
            <class>t2012e</class>
        </teacher>
    </user>
    <user>
        <employee id="2">
            <firstName>Phuong</firstName>
            <lastName>La</lastName>
            <email>Hanh@gmail.com</email>
            <phone>0123456789</phone>
            <age>20</age>
            <position>dev</position>
            <department>IT</department>
        </employee>
    </user>
    <user>
        <employee id="3">
            <firstName>Bach</firstName>
            <lastName>Nguyen Tung</lastName>
            <email>Bach@gmail.com</email>
            <phone>0321654987</phone>
            <age>20</age>
            <position>dev</position>
            <department>IT</department>
        </employee>
    </user>
    <user>
        <employee id="4">
            <firstName>Hoang Trung</firstName>
            <lastName>Kien</lastName>
            <email>Kien@gmail.com</email>
            <phone>9874561230</phone>
            <age>19</age>
            <position>dev</position>
            <department>IT</department>
        </employee>
    </user>
</users>
